### ISSUE TITLE
Timestamps mess with the numbers

### ISSUE THREAD

**Issue by Syphdias** [Tyrox92/Gw2SPECS#1]

**Comment by peteryao** [comment]
Alright so looking around charactergrid.cpp you can find - what I believe - is reading the images that are being taken.

This is done by examining the color of the image relative to 6E6E6E by comparing its RGB values to m_LowerRgbLimit (found in charactergrid.h), which is set to 110. 

This might explain how the time stamp is slipping through, its values aren't all above or below the check. I'll take a screenshot once I get back from school to see how the timestamp shows up, and we can just do a hard check for the color.

**Comment by Tyrox92** [comment]
Nice find! Will definetely look into this! Are you developing on the tool aswell?

**Comment by peteryao** [comment]
I'm pretty interested! I'm quite the beginner though, but I'll try to contribute what I can

**Comment by Tyrox92** [comment]
Any help is nice! Always appreciate if people help contribute to the final product we want everybody to use!

**Comment by Tyrox92** [comment]
After some investigation we figured out that "timestamp bug" is not as expected adding the time as damage value but randomly reading the previous 8-16 numbers and adding them again ...
It can happen that it creates a value that is
