### ISSUE TITLE
Hosted JS server

### ISSUE THREAD

**Issue by jsilvestre** [Tyrox92/Gw2SPECS#11]
Hey,

As we discussed in the game, and earlier in the other repository (https://github.com/Tyrox92/DPS_Server/issues/1), I have been working on a JavaScript implementation of the server.

We figured that the best way to combine our efforts would be to speak together about where we want to go. 
# Why going with an hosted version
- it's not easy, and not convenient to host the server at home, because the port forwarding thing is not something obvious for most people
- it can be self-hosted, and anyone can offer it as a service
- we could even package it with something like node-webkit, so it's still usable as an .exe for people who want that
# The next step

My idea is to have the summary available in the browser, rather than having a big fat UI directly in the game. Summary would be the dps value, the variation (+/-%) and graph comparing the last try, the best try and the current try. My focus is on individual willing to improve their DPS, not ranking people and risking a "shame and blame" effect.
Right now it only displays the summary of the try and the comparison with the previous try in a very raw manner.
I had to put together an "end of try" detection, which is a bit tricky (and clunky).

What is missing is a room management, to have the server hosts multiple raids at the same time.

Following Kozzy's work, my server is no longer compatible. I'm all for keeping up with the latest changes, but I'd preferer if we all go in the same direction.
I don't know what should be done exactly, maybe agreeing on a protocol spec could be a good start.

Cheers!

**Comment by peteryao** [comment]
Hey there, 

I agree strongly with setting up some hosted version, setting up the server per person is nonintuitive and I can imagine many people creating issues addressing individual cases, plus any updates we make to the DPS client could break their servers - something that would be better controlled on a hosted version.

On the note of keeping things in the same direction, perhaps we should agree on what we plan to ship, deciding that either through here or on some IRC/Slack channel?

**Comment by jsilvestre** [comment]
Sure, where should we meet to talk?

**Comment by DomGrieco** [comment]
You guys should talk with Kozzy. I'm not the greatest with JS, but I know Kozzy is doing most of the server updates.

We currently just added each other on in a skype group yesterday for quick communication. Let me know how you guys would like to communicate.

**Comment by jsilvestre** [comment]
Oh great, please add me too: joseph_silvestre

Thanks!
