### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by cproudlock** [Tyrox92/Gw2SPECS#25]
Hey, great release! I have two possible feature requests. 

1.) When I attempt to display the DPS meter on OBS with Window Capture, it's blacked out. [See example](http://imgur.com/fZHW3jA).

2.) I remember you guys mentioning the ability to use small interface / font in the future. Is this still being worked on?

Thanks again for the new DPS meter. It looks amazing!

**Comment by Tyrox92** [comment]
1) OBS doesnt like Transparent Background. Removed it and made a OBS_friendly version here:
http://gw2dps.com/wp-content/uploads/2016/02/GW2DPS_OBS_friendly_2.3.zip
1. Small Interface does work already! Small font is still something we want to do but it needs  a little time!

**Comment by cproudlock** [comment]
Thanks for the quick response, keep up the great work!
