### ISSUE TITLE
API:MumbleLink

### ISSUE THREAD

**Issue by bluelovers** [Tyrox92/Gw2SPECS#26]
how can use MumbleLink api for more info, auto fill name, class etc

[API:MumbleLink](https://wiki.guildwars2.com/wiki/API:MumbleLink)

**Comment by Syphdias** [comment]
This is a great idea. Let's say it's on the table ;)

**Comment by Eimhac** [comment]
Yeah nice idea!

**Comment by Tyrox92** [comment]
Next Major release.
