### ISSUE TITLE
If the screen resolution is too low the chat cannot be detected

### ISSUE THREAD

**Issue by Syphdias** [Tyrox92/Gw2SPECS#27]
If the screen resolution is at 1280x720 (or lower, presumably) is displays "Waiting"
If it is on 1440x900 (or higher, presumably) it works.

**Comment by Tyrox92** [comment]
A list of supported/unsupported Resolutions is made and will be published soonish.
At some point if the resolution is too small it changes text & interface appearance and the tool can't detect this yet.

Fix would be to make a pre-set for each changing resolution which is too much work right now.
~closed
