### ISSUE TITLE
Contact from Octavian

### ISSUE THREAD

**Issue by DomGrieco** [Tyrox92/Gw2SPECS#28]
I love your meter, fantastic work. My only gripe is that it's almost unusable with action camera. Because action camera just hides your cursor rather than getting rid of it, at some point during a raid encounter I will unwittingly move the mouse over the meter, click it, and drag it into the middle of the screen. I've had the meter cause a couple of wipes because myself or others in my party have done this at inopportune times. If there was some way to just minimize it completely so that players would have to deliberately click it to move it that would go a long way in making it usable for action camera players.

**Comment by Tyrox92** [comment]
Added CombatMode in 2.5
