### ISSUE TITLE
Contact from Arnaud

### ISSUE THREAD

**Issue by DomGrieco** [Tyrox92/Gw2SPECS#29]
I installed dps_server.exe under a dedicated server I own with wine, and it works.

But I have issues when a party member disconnects, when he connects again, we see his name twice ... that's weird.

**Comment by arnapou** [comment]
I can add informations about how the issue occurs. 

For that, I should explain my setup : I have a dedicated server with a personal vpn server (openvpn).
My computer has an openvpn client always connected, all my outgoing trafic go through the vpn.
I installed dps_server.exe on the dedicated server with wine.
My local vpn IP is something like 10.8.0.x.

**The problem**
When I connect my computer gw2dps client to the dps server, if I disconnect, or kill the client, my name stay on the server side : I guess the connection is not properly terminated. If I reconnect, I see my name twice, and so on ... I stopped after seing me 5 times.
I connect the gw2dps client to the server using its public IP (w.x.y.z)

If other people connect to the server, all is ok, they disapear if they disconnect.

**My guess**
I am seen with a "local" address 10.8.0.x on the dedicated server, where other people have standard public internet IPs. I think there is something around your IP/connection management on the dps server which cause that.

**Comment by arnapou** [comment]
**It works !** If I connect to the server using the local VPN IP address of the server, not the public IP address : 10.8.0.1 instead of w.x.y.z

The problem is solved for me. But you may have thing to manage to your side, or write these informations in a FAQ to help other people with a setup like mine.

**Comment by Tyrox92** [comment]
Glad you solved your Problems! Have fun and enjoy Gw2DPS. Thank you for providing suhc much info about this!
