### ISSUE TITLE
:-1: error: D8021 : invalid numeric argument '/Wno-reorder'

### ISSUE THREAD

**Issue by GW2Guy** [Tyrox92/Gw2SPECS#31]
Trying to build this, getting the following error 4 times.
`:-1: error: D8021 : invalid numeric argument '/Wno-reorder'`

Any suggestions on what I might be doing wrong?

**Comment by DomGrieco** [comment]
Did you install Qt with MinGW? Also usually is a warning, the '/Wno-reorder'.
