### ISSUE TITLE
Suggestion: Option for always on top

### ISSUE THREAD

**Issue by x04ty29er** [Tyrox92/Gw2SPECS#33]
Between release 2.3 and 2.4, the Qt:WindowStaysOnTopHint was removed from line 14 of configurator.cpp, which now reads:

this->setWindowFlags(Qt::FramelessWindowHint | Qt::Dialog);

I don't know enough about Qt to know why this was done, but it might be good to add this back as an option if possible.

**Comment by DomGrieco** [comment]
I removed it because it was redundant.

**Comment by x04ty29er** [comment]
Interesting. I did a bit more reading and it seems like it might conflict with Qt:FramelessWindowHint?

In any case, assuming the flag was redundant, I would expect the behaviour to be the same as it was before. However, this does not appear to be the case. The window is no longer always on top. It's possible that this is a win10 specific issue, but 2.3 stays on top and 2.4 does not, and the related change appears to be that flag.

**Comment by x04ty29er** [comment]
Just got it building and running on my Linux machine (built against Qt 5.4.2) and it seems to be always on top. Leads me to further believe this may be a Win10 related issue with Qt?

**Comment by Tyrox92** [comment]
Most recent developer version doesn't have it and it stays on top. Trying this on Win10. Not experiencing this with 2.4 either. Maybe this has something to do with the not always on top behaviour which will be fixed in future release

**Comment by x04ty29er** [comment]
No idea what happened, but it appears to stay on top properly now and i can't get it it repro. It is likely related to the issue you mentioned. I'll reopen and let you know if i find out more details.

Thanks.
